"""sales table

Revision ID: 2570f545dd05
Revises: eb919561b89d
Create Date: 2025-06-02 08:05:38.032895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2570f545dd05'
down_revision = 'eb919561b89d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('sale_price_at_time', sa.Float(), nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_sale_date'), ['sale_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_sale_date'))

    op.drop_table('sale')
    # ### end Alembic commands ###
