"""add cost_price_at_time_of_sale to sale

Revision ID: 3f5f01c2c3ee
Revises: 2570f545dd05
Create Date: 2025-06-02 08:08:23.847681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5f01c2c3ee'
down_revision = '2570f545dd05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price_at_time_of_sale', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('cost_price_at_time_of_sale')

    # ### end Alembic commands ###
