"""purchases table

Revision ID: eb919561b89d
Revises: c6fa929d6958
Create Date: 2025-06-02 08:03:15.027951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb919561b89d'
down_revision = 'c6fa929d6958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price_at_time', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_purchase_date'), ['purchase_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_purchase_date'))

    op.drop_table('purchase')
    # ### end Alembic commands ###
